[build]
base = "."
command = "npm --prefix \"valentine-main/valentine's-for-riah (2)\" install && npm --prefix \"valentine-main/valentine's-for-riah (2)\" run build"
publish = "valentine-main/valentine's-for-riah (2)/dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
