[build]
base = "valentine-main"
command = "npm --prefix \"valentine's-for-riah (2)\" install && npm --prefix \"valentine's-for-riah (2)\" run build"
publish = "valentine's-for-riah (2)/dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
